name: âœ… check
on: push
jobs:
  lint:
    name: ğŸ§¹ lint
    runs-on: macos-latest
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: âš™ï¸ Install jsonlint
        run: |
          brew install jsonlint | tee
      - name: ğŸ§¹ Manifest Lint
        run: |
          cat manifest.json | jsonlint

